spring.application.name=ms-register-hexa
spring.datasource.url=jdbc:postgresql://localhost:5432/hexagonalG14
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
token.api=sk_7701.y0uLrT7FJyzCkN2zotD3R23j02ZMYoRU